// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: serialization.proto

package serialization

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event Types Enum
type EventType int32

const (
	EventType_UNKNOWN                EventType = 0
	EventType_EVENT_FLASH            EventType = 1
	EventType_EVENT_SMOKE_START      EventType = 2
	EventType_EVENT_SMOKE_END        EventType = 3
	EventType_EVENT_KILL             EventType = 4
	EventType_EVENT_HE               EventType = 5
	EventType_EVENT_TEAM_CHANGE      EventType = 6
	EventType_EVENT_INFERNO          EventType = 7
	EventType_EVENT_DAMAGE           EventType = 8
	EventType_EVENT_PLAYER_FLASHED   EventType = 9
	EventType_EVENT_EQUIPMENT_UPDATE EventType = 10
	EventType_EVENT_PICKUP           EventType = 11
	EventType_EVENT_DROP             EventType = 12
	EventType_EVENT_BOMB_DROPPED     EventType = 13
	EventType_EVENT_BOMB_PICKUP      EventType = 14
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "EVENT_FLASH",
		2:  "EVENT_SMOKE_START",
		3:  "EVENT_SMOKE_END",
		4:  "EVENT_KILL",
		5:  "EVENT_HE",
		6:  "EVENT_TEAM_CHANGE",
		7:  "EVENT_INFERNO",
		8:  "EVENT_DAMAGE",
		9:  "EVENT_PLAYER_FLASHED",
		10: "EVENT_EQUIPMENT_UPDATE",
		11: "EVENT_PICKUP",
		12: "EVENT_DROP",
		13: "EVENT_BOMB_DROPPED",
		14: "EVENT_BOMB_PICKUP",
	}
	EventType_value = map[string]int32{
		"UNKNOWN":                0,
		"EVENT_FLASH":            1,
		"EVENT_SMOKE_START":      2,
		"EVENT_SMOKE_END":        3,
		"EVENT_KILL":             4,
		"EVENT_HE":               5,
		"EVENT_TEAM_CHANGE":      6,
		"EVENT_INFERNO":          7,
		"EVENT_DAMAGE":           8,
		"EVENT_PLAYER_FLASHED":   9,
		"EVENT_EQUIPMENT_UPDATE": 10,
		"EVENT_PICKUP":           11,
		"EVENT_DROP":             12,
		"EVENT_BOMB_DROPPED":     13,
		"EVENT_BOMB_PICKUP":      14,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_serialization_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_serialization_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0}
}

type PlayerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMetadata) Reset() {
	*x = PlayerMetadata{}
	mi := &file_serialization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMetadata) ProtoMessage() {}

func (x *PlayerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMetadata.ProtoReflect.Descriptor instead.
func (*PlayerMetadata) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NadeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Thrower       int32                  `protobuf:"varint,2,opt,name=thrower,proto3" json:"thrower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NadeMetadata) Reset() {
	*x = NadeMetadata{}
	mi := &file_serialization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NadeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NadeMetadata) ProtoMessage() {}

func (x *NadeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NadeMetadata.ProtoReflect.Descriptor instead.
func (*NadeMetadata) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{1}
}

func (x *NadeMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NadeMetadata) GetThrower() int32 {
	if x != nil {
		return x.Thrower
	}
	return 0
}

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ct            int32                  `protobuf:"varint,1,opt,name=ct,proto3" json:"ct,omitempty"`
	T             int32                  `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_serialization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{2}
}

func (x *Score) GetCt() int32 {
	if x != nil {
		return x.Ct
	}
	return 0
}

func (x *Score) GetT() int32 {
	if x != nil {
		return x.T
	}
	return 0
}

type RoundMetadata struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Score             *Score                     `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	PlayerToTeam      map[int32]int32            `protobuf:"bytes,2,rep,name=playerToTeam,proto3" json:"playerToTeam,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PlayerToEquipment map[int32]*PlayerEquipment `protobuf:"bytes,3,rep,name=playerToEquipment,proto3" json:"playerToEquipment,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoundMetadata) Reset() {
	*x = RoundMetadata{}
	mi := &file_serialization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundMetadata) ProtoMessage() {}

func (x *RoundMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundMetadata.ProtoReflect.Descriptor instead.
func (*RoundMetadata) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{3}
}

func (x *RoundMetadata) GetScore() *Score {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *RoundMetadata) GetPlayerToTeam() map[int32]int32 {
	if x != nil {
		return x.PlayerToTeam
	}
	return nil
}

func (x *RoundMetadata) GetPlayerToEquipment() map[int32]*PlayerEquipment {
	if x != nil {
		return x.PlayerToEquipment
	}
	return nil
}

type PlayerPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Yaw           float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPosition) Reset() {
	*x = PlayerPosition{}
	mi := &file_serialization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPosition) ProtoMessage() {}

func (x *PlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPosition.ProtoReflect.Descriptor instead.
func (*PlayerPosition) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerPosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerPosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerPosition) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type NadePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NadePosition) Reset() {
	*x = NadePosition{}
	mi := &file_serialization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NadePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NadePosition) ProtoMessage() {}

func (x *NadePosition) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NadePosition.ProtoReflect.Descriptor instead.
func (*NadePosition) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{5}
}

func (x *NadePosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NadePosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FrameData struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	PlayerPositions map[int32]*PlayerPosition `protobuf:"bytes,1,rep,name=playerPositions,proto3" json:"playerPositions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NadePositions   map[string]*NadePosition  `protobuf:"bytes,2,rep,name=nadePositions,proto3" json:"nadePositions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_serialization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{6}
}

func (x *FrameData) GetPlayerPositions() map[int32]*PlayerPosition {
	if x != nil {
		return x.PlayerPositions
	}
	return nil
}

func (x *FrameData) GetNadePositions() map[string]*NadePosition {
	if x != nil {
		return x.NadePositions
	}
	return nil
}

type PlayerEquipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equipment     []string               `protobuf:"bytes,1,rep,name=equipment,proto3" json:"equipment,omitempty"`
	Money         int32                  `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	Armor         int32                  `protobuf:"varint,3,opt,name=armor,proto3" json:"armor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEquipment) Reset() {
	*x = PlayerEquipment{}
	mi := &file_serialization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEquipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEquipment) ProtoMessage() {}

func (x *PlayerEquipment) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEquipment.ProtoReflect.Descriptor instead.
func (*PlayerEquipment) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerEquipment) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *PlayerEquipment) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *PlayerEquipment) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

type PlayerSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Yaw           float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Health        int32                  `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	Armor         int32                  `protobuf:"varint,5,opt,name=armor,proto3" json:"armor,omitempty"`
	Team          int32                  `protobuf:"varint,6,opt,name=team,proto3" json:"team,omitempty"`
	Money         int32                  `protobuf:"varint,7,opt,name=money,proto3" json:"money,omitempty"`
	Equipment     []string               `protobuf:"bytes,8,rep,name=equipment,proto3" json:"equipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSnapshot) Reset() {
	*x = PlayerSnapshot{}
	mi := &file_serialization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSnapshot) ProtoMessage() {}

func (x *PlayerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerSnapshot) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerSnapshot) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerSnapshot) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerSnapshot) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerSnapshot) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerSnapshot) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *PlayerSnapshot) GetTeam() int32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *PlayerSnapshot) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *PlayerSnapshot) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type BloomSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloomSnapshot) Reset() {
	*x = BloomSnapshot{}
	mi := &file_serialization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomSnapshot) ProtoMessage() {}

func (x *BloomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomSnapshot.ProtoReflect.Descriptor instead.
func (*BloomSnapshot) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{9}
}

func (x *BloomSnapshot) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BloomSnapshot) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BloomSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BloomSnapshot) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type FlashedSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemainingTime float64                `protobuf:"fixed64,1,opt,name=remainingTime,proto3" json:"remainingTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashedSnapshot) Reset() {
	*x = FlashedSnapshot{}
	mi := &file_serialization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashedSnapshot) ProtoMessage() {}

func (x *FlashedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashedSnapshot.ProtoReflect.Descriptor instead.
func (*FlashedSnapshot) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{10}
}

func (x *FlashedSnapshot) GetRemainingTime() float64 {
	if x != nil {
		return x.RemainingTime
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_serialization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{11}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Points struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Points) Reset() {
	*x = Points{}
	mi := &file_serialization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Points) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Points) ProtoMessage() {}

func (x *Points) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Points.ProtoReflect.Descriptor instead.
func (*Points) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{12}
}

func (x *Points) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type ULID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           uint64                 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          uint64                 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ULID) Reset() {
	*x = ULID{}
	mi := &file_serialization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ULID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ULID) ProtoMessage() {}

func (x *ULID) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ULID.ProtoReflect.Descriptor instead.
func (*ULID) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{13}
}

func (x *ULID) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ULID) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type Snapshot struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Tick             int32                      `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	PlayerSnapshots  map[int32]*PlayerSnapshot  `protobuf:"bytes,2,rep,name=playerSnapshots,proto3" json:"playerSnapshots,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BloomSnapshots   map[string]*BloomSnapshot  `protobuf:"bytes,3,rep,name=bloomSnapshots,proto3" json:"bloomSnapshots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InfernoSnapshots map[int64]*Points          `protobuf:"bytes,4,rep,name=infernoSnapshots,proto3" json:"infernoSnapshots,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FlashedSnapshots map[int32]*FlashedSnapshot `protobuf:"bytes,5,rep,name=flashedSnapshots,proto3" json:"flashedSnapshots,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BombSnapshot     *Point                     `protobuf:"bytes,6,opt,name=bombSnapshot,proto3" json:"bombSnapshot,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_serialization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{14}
}

func (x *Snapshot) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Snapshot) GetPlayerSnapshots() map[int32]*PlayerSnapshot {
	if x != nil {
		return x.PlayerSnapshots
	}
	return nil
}

func (x *Snapshot) GetBloomSnapshots() map[string]*BloomSnapshot {
	if x != nil {
		return x.BloomSnapshots
	}
	return nil
}

func (x *Snapshot) GetInfernoSnapshots() map[int64]*Points {
	if x != nil {
		return x.InfernoSnapshots
	}
	return nil
}

func (x *Snapshot) GetFlashedSnapshots() map[int32]*FlashedSnapshot {
	if x != nil {
		return x.FlashedSnapshots
	}
	return nil
}

func (x *Snapshot) GetBombSnapshot() *Point {
	if x != nil {
		return x.BombSnapshot
	}
	return nil
}

// Event Messages
type TeamChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int32                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Team          int32                  `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamChangeEvent) Reset() {
	*x = TeamChangeEvent{}
	mi := &file_serialization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamChangeEvent) ProtoMessage() {}

func (x *TeamChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamChangeEvent.ProtoReflect.Descriptor instead.
func (*TeamChangeEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{15}
}

func (x *TeamChangeEvent) GetPlayerID() int32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *TeamChangeEvent) GetTeam() int32 {
	if x != nil {
		return x.Team
	}
	return 0
}

type SmokeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	NadeId        string                 `protobuf:"bytes,3,opt,name=nadeId,proto3" json:"nadeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmokeEvent) Reset() {
	*x = SmokeEvent{}
	mi := &file_serialization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmokeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmokeEvent) ProtoMessage() {}

func (x *SmokeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmokeEvent.ProtoReflect.Descriptor instead.
func (*SmokeEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{16}
}

func (x *SmokeEvent) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SmokeEvent) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SmokeEvent) GetNadeId() string {
	if x != nil {
		return x.NadeId
	}
	return ""
}

type GrenadeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	NadeId        string                 `protobuf:"bytes,3,opt,name=nadeId,proto3" json:"nadeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrenadeEvent) Reset() {
	*x = GrenadeEvent{}
	mi := &file_serialization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrenadeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrenadeEvent) ProtoMessage() {}

func (x *GrenadeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrenadeEvent.ProtoReflect.Descriptor instead.
func (*GrenadeEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{17}
}

func (x *GrenadeEvent) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GrenadeEvent) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GrenadeEvent) GetNadeId() string {
	if x != nil {
		return x.NadeId
	}
	return ""
}

type KillEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VictimID      int32                  `protobuf:"varint,1,opt,name=victimID,proto3" json:"victimID,omitempty"`
	AttackerID    int32                  `protobuf:"varint,2,opt,name=attackerID,proto3" json:"attackerID,omitempty"`
	AssisterID    int32                  `protobuf:"varint,3,opt,name=assisterID,proto3" json:"assisterID,omitempty"`
	Weapon        string                 `protobuf:"bytes,4,opt,name=weapon,proto3" json:"weapon,omitempty"`
	IsWallbang    bool                   `protobuf:"varint,5,opt,name=isWallbang,proto3" json:"isWallbang,omitempty"`
	IsHeadshot    bool                   `protobuf:"varint,6,opt,name=isHeadshot,proto3" json:"isHeadshot,omitempty"`
	AssistedFlash bool                   `protobuf:"varint,7,opt,name=assistedFlash,proto3" json:"assistedFlash,omitempty"`
	AttackerBlind bool                   `protobuf:"varint,8,opt,name=attackerBlind,proto3" json:"attackerBlind,omitempty"`
	NoScope       bool                   `protobuf:"varint,9,opt,name=noScope,proto3" json:"noScope,omitempty"`
	ThroughSmoke  bool                   `protobuf:"varint,10,opt,name=throughSmoke,proto3" json:"throughSmoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillEvent) Reset() {
	*x = KillEvent{}
	mi := &file_serialization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillEvent) ProtoMessage() {}

func (x *KillEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillEvent.ProtoReflect.Descriptor instead.
func (*KillEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{18}
}

func (x *KillEvent) GetVictimID() int32 {
	if x != nil {
		return x.VictimID
	}
	return 0
}

func (x *KillEvent) GetAttackerID() int32 {
	if x != nil {
		return x.AttackerID
	}
	return 0
}

func (x *KillEvent) GetAssisterID() int32 {
	if x != nil {
		return x.AssisterID
	}
	return 0
}

func (x *KillEvent) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *KillEvent) GetIsWallbang() bool {
	if x != nil {
		return x.IsWallbang
	}
	return false
}

func (x *KillEvent) GetIsHeadshot() bool {
	if x != nil {
		return x.IsHeadshot
	}
	return false
}

func (x *KillEvent) GetAssistedFlash() bool {
	if x != nil {
		return x.AssistedFlash
	}
	return false
}

func (x *KillEvent) GetAttackerBlind() bool {
	if x != nil {
		return x.AttackerBlind
	}
	return false
}

func (x *KillEvent) GetNoScope() bool {
	if x != nil {
		return x.NoScope
	}
	return false
}

func (x *KillEvent) GetThroughSmoke() bool {
	if x != nil {
		return x.ThroughSmoke
	}
	return false
}

type DamageEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerID          int32                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Health            int32                  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Armor             int32                  `protobuf:"varint,3,opt,name=armor,proto3" json:"armor,omitempty"`
	HealthDamageTaken int32                  `protobuf:"varint,4,opt,name=healthDamageTaken,proto3" json:"healthDamageTaken,omitempty"`
	ArmorDamageTaken  int32                  `protobuf:"varint,5,opt,name=armorDamageTaken,proto3" json:"armorDamageTaken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DamageEvent) Reset() {
	*x = DamageEvent{}
	mi := &file_serialization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageEvent) ProtoMessage() {}

func (x *DamageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageEvent.ProtoReflect.Descriptor instead.
func (*DamageEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{19}
}

func (x *DamageEvent) GetPlayerID() int32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *DamageEvent) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *DamageEvent) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *DamageEvent) GetHealthDamageTaken() int32 {
	if x != nil {
		return x.HealthDamageTaken
	}
	return 0
}

func (x *DamageEvent) GetArmorDamageTaken() int32 {
	if x != nil {
		return x.ArmorDamageTaken
	}
	return 0
}

type InfernoEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	NadeId        int64                  `protobuf:"varint,2,opt,name=nadeId,proto3" json:"nadeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfernoEvent) Reset() {
	*x = InfernoEvent{}
	mi := &file_serialization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfernoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfernoEvent) ProtoMessage() {}

func (x *InfernoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfernoEvent.ProtoReflect.Descriptor instead.
func (*InfernoEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{20}
}

func (x *InfernoEvent) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *InfernoEvent) GetNadeId() int64 {
	if x != nil {
		return x.NadeId
	}
	return 0
}

type FlashEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int32                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashEvent) Reset() {
	*x = FlashEvent{}
	mi := &file_serialization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashEvent) ProtoMessage() {}

func (x *FlashEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashEvent.ProtoReflect.Descriptor instead.
func (*FlashEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{21}
}

func (x *FlashEvent) GetPlayerID() int32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *FlashEvent) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type EquipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int32                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Money         int32                  `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	Equipment     []string               `protobuf:"bytes,3,rep,name=equipment,proto3" json:"equipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentEvent) Reset() {
	*x = EquipmentEvent{}
	mi := &file_serialization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentEvent) ProtoMessage() {}

func (x *EquipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentEvent.ProtoReflect.Descriptor instead.
func (*EquipmentEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{22}
}

func (x *EquipmentEvent) GetPlayerID() int32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *EquipmentEvent) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *EquipmentEvent) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type PickupEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipmentID   string                 `protobuf:"bytes,1,opt,name=equipmentID,proto3" json:"equipmentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupEvent) Reset() {
	*x = PickupEvent{}
	mi := &file_serialization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupEvent) ProtoMessage() {}

func (x *PickupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupEvent.ProtoReflect.Descriptor instead.
func (*PickupEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{23}
}

func (x *PickupEvent) GetEquipmentID() string {
	if x != nil {
		return x.EquipmentID
	}
	return ""
}

type DropEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipmentID   string                 `protobuf:"bytes,1,opt,name=equipmentID,proto3" json:"equipmentID,omitempty"`
	EquipmentName string                 `protobuf:"bytes,2,opt,name=equipmentName,proto3" json:"equipmentName,omitempty"`
	Position      *Point                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropEvent) Reset() {
	*x = DropEvent{}
	mi := &file_serialization_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropEvent) ProtoMessage() {}

func (x *DropEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropEvent.ProtoReflect.Descriptor instead.
func (*DropEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{24}
}

func (x *DropEvent) GetEquipmentID() string {
	if x != nil {
		return x.EquipmentID
	}
	return ""
}

func (x *DropEvent) GetEquipmentName() string {
	if x != nil {
		return x.EquipmentName
	}
	return ""
}

func (x *DropEvent) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

type BombDroppedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Point                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BombDroppedEvent) Reset() {
	*x = BombDroppedEvent{}
	mi := &file_serialization_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BombDroppedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BombDroppedEvent) ProtoMessage() {}

func (x *BombDroppedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BombDroppedEvent.ProtoReflect.Descriptor instead.
func (*BombDroppedEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{25}
}

func (x *BombDroppedEvent) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

type GameEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tick  int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Type  EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=serialization.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*GameEvent_TeamChangeEvent
	//	*GameEvent_SmokeEvent
	//	*GameEvent_GrenadeEvent
	//	*GameEvent_KillEvent
	//	*GameEvent_FlashEvent
	//	*GameEvent_DamageEvent
	//	*GameEvent_InfernoEvent
	//	*GameEvent_EquipmentEvent
	//	*GameEvent_PickupEvent
	//	*GameEvent_DropEvent
	//	*GameEvent_BombDroppedEvent
	Data          isGameEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_serialization_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{26}
}

func (x *GameEvent) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_UNKNOWN
}

func (x *GameEvent) GetData() isGameEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GameEvent) GetTeamChangeEvent() *TeamChangeEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_TeamChangeEvent); ok {
			return x.TeamChangeEvent
		}
	}
	return nil
}

func (x *GameEvent) GetSmokeEvent() *SmokeEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_SmokeEvent); ok {
			return x.SmokeEvent
		}
	}
	return nil
}

func (x *GameEvent) GetGrenadeEvent() *GrenadeEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_GrenadeEvent); ok {
			return x.GrenadeEvent
		}
	}
	return nil
}

func (x *GameEvent) GetKillEvent() *KillEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_KillEvent); ok {
			return x.KillEvent
		}
	}
	return nil
}

func (x *GameEvent) GetFlashEvent() *FlashEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_FlashEvent); ok {
			return x.FlashEvent
		}
	}
	return nil
}

func (x *GameEvent) GetDamageEvent() *DamageEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_DamageEvent); ok {
			return x.DamageEvent
		}
	}
	return nil
}

func (x *GameEvent) GetInfernoEvent() *InfernoEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_InfernoEvent); ok {
			return x.InfernoEvent
		}
	}
	return nil
}

func (x *GameEvent) GetEquipmentEvent() *EquipmentEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_EquipmentEvent); ok {
			return x.EquipmentEvent
		}
	}
	return nil
}

func (x *GameEvent) GetPickupEvent() *PickupEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_PickupEvent); ok {
			return x.PickupEvent
		}
	}
	return nil
}

func (x *GameEvent) GetDropEvent() *DropEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_DropEvent); ok {
			return x.DropEvent
		}
	}
	return nil
}

func (x *GameEvent) GetBombDroppedEvent() *BombDroppedEvent {
	if x != nil {
		if x, ok := x.Data.(*GameEvent_BombDroppedEvent); ok {
			return x.BombDroppedEvent
		}
	}
	return nil
}

type isGameEvent_Data interface {
	isGameEvent_Data()
}

type GameEvent_TeamChangeEvent struct {
	TeamChangeEvent *TeamChangeEvent `protobuf:"bytes,3,opt,name=teamChangeEvent,proto3,oneof"`
}

type GameEvent_SmokeEvent struct {
	SmokeEvent *SmokeEvent `protobuf:"bytes,4,opt,name=smokeEvent,proto3,oneof"`
}

type GameEvent_GrenadeEvent struct {
	GrenadeEvent *GrenadeEvent `protobuf:"bytes,5,opt,name=grenadeEvent,proto3,oneof"`
}

type GameEvent_KillEvent struct {
	KillEvent *KillEvent `protobuf:"bytes,6,opt,name=killEvent,proto3,oneof"`
}

type GameEvent_FlashEvent struct {
	FlashEvent *FlashEvent `protobuf:"bytes,7,opt,name=flashEvent,proto3,oneof"`
}

type GameEvent_DamageEvent struct {
	DamageEvent *DamageEvent `protobuf:"bytes,8,opt,name=damageEvent,proto3,oneof"`
}

type GameEvent_InfernoEvent struct {
	InfernoEvent *InfernoEvent `protobuf:"bytes,9,opt,name=infernoEvent,proto3,oneof"`
}

type GameEvent_EquipmentEvent struct {
	EquipmentEvent *EquipmentEvent `protobuf:"bytes,10,opt,name=equipmentEvent,proto3,oneof"`
}

type GameEvent_PickupEvent struct {
	PickupEvent *PickupEvent `protobuf:"bytes,11,opt,name=pickupEvent,proto3,oneof"`
}

type GameEvent_DropEvent struct {
	DropEvent *DropEvent `protobuf:"bytes,12,opt,name=dropEvent,proto3,oneof"`
}

type GameEvent_BombDroppedEvent struct {
	BombDroppedEvent *BombDroppedEvent `protobuf:"bytes,13,opt,name=bombDroppedEvent,proto3,oneof"`
}

func (*GameEvent_TeamChangeEvent) isGameEvent_Data() {}

func (*GameEvent_SmokeEvent) isGameEvent_Data() {}

func (*GameEvent_GrenadeEvent) isGameEvent_Data() {}

func (*GameEvent_KillEvent) isGameEvent_Data() {}

func (*GameEvent_FlashEvent) isGameEvent_Data() {}

func (*GameEvent_DamageEvent) isGameEvent_Data() {}

func (*GameEvent_InfernoEvent) isGameEvent_Data() {}

func (*GameEvent_EquipmentEvent) isGameEvent_Data() {}

func (*GameEvent_PickupEvent) isGameEvent_Data() {}

func (*GameEvent_DropEvent) isGameEvent_Data() {}

func (*GameEvent_BombDroppedEvent) isGameEvent_Data() {}

type RoundFrames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*FrameData           `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundFrames) Reset() {
	*x = RoundFrames{}
	mi := &file_serialization_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundFrames) ProtoMessage() {}

func (x *RoundFrames) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundFrames.ProtoReflect.Descriptor instead.
func (*RoundFrames) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{27}
}

func (x *RoundFrames) GetFrames() []*FrameData {
	if x != nil {
		return x.Frames
	}
	return nil
}

type RoundEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GameEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundEvents) Reset() {
	*x = RoundEvents{}
	mi := &file_serialization_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundEvents) ProtoMessage() {}

func (x *RoundEvents) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundEvents.ProtoReflect.Descriptor instead.
func (*RoundEvents) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{28}
}

func (x *RoundEvents) GetEvents() []*GameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RoundSnapshots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundSnapshots) Reset() {
	*x = RoundSnapshots{}
	mi := &file_serialization_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundSnapshots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundSnapshots) ProtoMessage() {}

func (x *RoundSnapshots) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundSnapshots.ProtoReflect.Descriptor instead.
func (*RoundSnapshots) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{29}
}

func (x *RoundSnapshots) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type Replay struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	MapName         string                    `protobuf:"bytes,1,opt,name=mapName,proto3" json:"mapName,omitempty"`
	TickRate        float64                   `protobuf:"fixed64,2,opt,name=tickRate,proto3" json:"tickRate,omitempty"`
	PlayersMetadata map[int32]*PlayerMetadata `protobuf:"bytes,3,rep,name=playersMetadata,proto3" json:"playersMetadata,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NadesMetadata   map[string]*NadeMetadata  `protobuf:"bytes,4,rep,name=nadesMetadata,proto3" json:"nadesMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RoundsMetadata  []*RoundMetadata          `protobuf:"bytes,5,rep,name=roundsMetadata,proto3" json:"roundsMetadata,omitempty"`
	Rounds          []*RoundFrames            `protobuf:"bytes,6,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Events          []*RoundEvents            `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	Snapshots       []*RoundSnapshots         `protobuf:"bytes,8,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	LastUpdated     *timestamp.Timestamp      `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Replay) Reset() {
	*x = Replay{}
	mi := &file_serialization_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay) ProtoMessage() {}

func (x *Replay) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay.ProtoReflect.Descriptor instead.
func (*Replay) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{30}
}

func (x *Replay) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *Replay) GetTickRate() float64 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Replay) GetPlayersMetadata() map[int32]*PlayerMetadata {
	if x != nil {
		return x.PlayersMetadata
	}
	return nil
}

func (x *Replay) GetNadesMetadata() map[string]*NadeMetadata {
	if x != nil {
		return x.NadesMetadata
	}
	return nil
}

func (x *Replay) GetRoundsMetadata() []*RoundMetadata {
	if x != nil {
		return x.RoundsMetadata
	}
	return nil
}

func (x *Replay) GetRounds() []*RoundFrames {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *Replay) GetEvents() []*RoundEvents {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Replay) GetSnapshots() []*RoundSnapshots {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *Replay) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_serialization_proto protoreflect.FileDescriptor

const file_serialization_proto_rawDesc = "" +
	"\n" +
	"\x13serialization.proto\x12\rserialization\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x0ePlayerMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\fNadeMetadata\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\athrower\x18\x02 \x01(\x05R\athrower\"%\n" +
	"\x05Score\x12\x0e\n" +
	"\x02ct\x18\x01 \x01(\x05R\x02ct\x12\f\n" +
	"\x01t\x18\x02 \x01(\x05R\x01t\"\x99\x03\n" +
	"\rRoundMetadata\x12*\n" +
	"\x05score\x18\x01 \x01(\v2\x14.serialization.ScoreR\x05score\x12R\n" +
	"\fplayerToTeam\x18\x02 \x03(\v2..serialization.RoundMetadata.PlayerToTeamEntryR\fplayerToTeam\x12a\n" +
	"\x11playerToEquipment\x18\x03 \x03(\v23.serialization.RoundMetadata.PlayerToEquipmentEntryR\x11playerToEquipment\x1a?\n" +
	"\x11PlayerToTeamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1ad\n" +
	"\x16PlayerToEquipmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.serialization.PlayerEquipmentR\x05value:\x028\x01\">\n" +
	"\x0ePlayerPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x02R\x03yaw\"*\n" +
	"\fNadePosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\xf9\x02\n" +
	"\tFrameData\x12W\n" +
	"\x0fplayerPositions\x18\x01 \x03(\v2-.serialization.FrameData.PlayerPositionsEntryR\x0fplayerPositions\x12Q\n" +
	"\rnadePositions\x18\x02 \x03(\v2+.serialization.FrameData.NadePositionsEntryR\rnadePositions\x1aa\n" +
	"\x14PlayerPositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.serialization.PlayerPositionR\x05value:\x028\x01\x1a]\n" +
	"\x12NadePositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.serialization.NadePositionR\x05value:\x028\x01\"[\n" +
	"\x0fPlayerEquipment\x12\x1c\n" +
	"\tequipment\x18\x01 \x03(\tR\tequipment\x12\x14\n" +
	"\x05money\x18\x02 \x01(\x05R\x05money\x12\x14\n" +
	"\x05armor\x18\x03 \x01(\x05R\x05armor\"\xb4\x01\n" +
	"\x0ePlayerSnapshot\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x02R\x03yaw\x12\x16\n" +
	"\x06health\x18\x04 \x01(\x05R\x06health\x12\x14\n" +
	"\x05armor\x18\x05 \x01(\x05R\x05armor\x12\x12\n" +
	"\x04team\x18\x06 \x01(\x05R\x04team\x12\x14\n" +
	"\x05money\x18\a \x01(\x05R\x05money\x12\x1c\n" +
	"\tequipment\x18\b \x03(\tR\tequipment\"[\n" +
	"\rBloomSnapshot\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\"7\n" +
	"\x0fFlashedSnapshot\x12$\n" +
	"\rremainingTime\x18\x01 \x01(\x01R\rremainingTime\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"6\n" +
	"\x06Points\x12,\n" +
	"\x06points\x18\x01 \x03(\v2\x14.serialization.PointR\x06points\",\n" +
	"\x04ULID\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x04R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x04R\x04high\"\xc0\x06\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12V\n" +
	"\x0fplayerSnapshots\x18\x02 \x03(\v2,.serialization.Snapshot.PlayerSnapshotsEntryR\x0fplayerSnapshots\x12S\n" +
	"\x0ebloomSnapshots\x18\x03 \x03(\v2+.serialization.Snapshot.BloomSnapshotsEntryR\x0ebloomSnapshots\x12Y\n" +
	"\x10infernoSnapshots\x18\x04 \x03(\v2-.serialization.Snapshot.InfernoSnapshotsEntryR\x10infernoSnapshots\x12Y\n" +
	"\x10flashedSnapshots\x18\x05 \x03(\v2-.serialization.Snapshot.FlashedSnapshotsEntryR\x10flashedSnapshots\x128\n" +
	"\fbombSnapshot\x18\x06 \x01(\v2\x14.serialization.PointR\fbombSnapshot\x1aa\n" +
	"\x14PlayerSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.serialization.PlayerSnapshotR\x05value:\x028\x01\x1a_\n" +
	"\x13BloomSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.serialization.BloomSnapshotR\x05value:\x028\x01\x1aZ\n" +
	"\x15InfernoSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.serialization.PointsR\x05value:\x028\x01\x1ac\n" +
	"\x15FlashedSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.serialization.FlashedSnapshotR\x05value:\x028\x01\"A\n" +
	"\x0fTeamChangeEvent\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x05R\bplayerID\x12\x12\n" +
	"\x04team\x18\x02 \x01(\x05R\x04team\"@\n" +
	"\n" +
	"SmokeEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x16\n" +
	"\x06nadeId\x18\x03 \x01(\tR\x06nadeId\"B\n" +
	"\fGrenadeEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x16\n" +
	"\x06nadeId\x18\x03 \x01(\tR\x06nadeId\"\xc9\x02\n" +
	"\tKillEvent\x12\x1a\n" +
	"\bvictimID\x18\x01 \x01(\x05R\bvictimID\x12\x1e\n" +
	"\n" +
	"attackerID\x18\x02 \x01(\x05R\n" +
	"attackerID\x12\x1e\n" +
	"\n" +
	"assisterID\x18\x03 \x01(\x05R\n" +
	"assisterID\x12\x16\n" +
	"\x06weapon\x18\x04 \x01(\tR\x06weapon\x12\x1e\n" +
	"\n" +
	"isWallbang\x18\x05 \x01(\bR\n" +
	"isWallbang\x12\x1e\n" +
	"\n" +
	"isHeadshot\x18\x06 \x01(\bR\n" +
	"isHeadshot\x12$\n" +
	"\rassistedFlash\x18\a \x01(\bR\rassistedFlash\x12$\n" +
	"\rattackerBlind\x18\b \x01(\bR\rattackerBlind\x12\x18\n" +
	"\anoScope\x18\t \x01(\bR\anoScope\x12\"\n" +
	"\fthroughSmoke\x18\n" +
	" \x01(\bR\fthroughSmoke\"\xb1\x01\n" +
	"\vDamageEvent\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x05R\bplayerID\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x05R\x06health\x12\x14\n" +
	"\x05armor\x18\x03 \x01(\x05R\x05armor\x12,\n" +
	"\x11healthDamageTaken\x18\x04 \x01(\x05R\x11healthDamageTaken\x12*\n" +
	"\x10armorDamageTaken\x18\x05 \x01(\x05R\x10armorDamageTaken\"T\n" +
	"\fInfernoEvent\x12,\n" +
	"\x06points\x18\x01 \x03(\v2\x14.serialization.PointR\x06points\x12\x16\n" +
	"\x06nadeId\x18\x02 \x01(\x03R\x06nadeId\"D\n" +
	"\n" +
	"FlashEvent\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x05R\bplayerID\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\"`\n" +
	"\x0eEquipmentEvent\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x05R\bplayerID\x12\x14\n" +
	"\x05money\x18\x02 \x01(\x05R\x05money\x12\x1c\n" +
	"\tequipment\x18\x03 \x03(\tR\tequipment\"/\n" +
	"\vPickupEvent\x12 \n" +
	"\vequipmentID\x18\x01 \x01(\tR\vequipmentID\"\x85\x01\n" +
	"\tDropEvent\x12 \n" +
	"\vequipmentID\x18\x01 \x01(\tR\vequipmentID\x12$\n" +
	"\requipmentName\x18\x02 \x01(\tR\requipmentName\x120\n" +
	"\bposition\x18\x03 \x01(\v2\x14.serialization.PointR\bposition\"D\n" +
	"\x10BombDroppedEvent\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.serialization.PointR\bposition\"\xad\x06\n" +
	"\tGameEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.serialization.EventTypeR\x04type\x12J\n" +
	"\x0fteamChangeEvent\x18\x03 \x01(\v2\x1e.serialization.TeamChangeEventH\x00R\x0fteamChangeEvent\x12;\n" +
	"\n" +
	"smokeEvent\x18\x04 \x01(\v2\x19.serialization.SmokeEventH\x00R\n" +
	"smokeEvent\x12A\n" +
	"\fgrenadeEvent\x18\x05 \x01(\v2\x1b.serialization.GrenadeEventH\x00R\fgrenadeEvent\x128\n" +
	"\tkillEvent\x18\x06 \x01(\v2\x18.serialization.KillEventH\x00R\tkillEvent\x12;\n" +
	"\n" +
	"flashEvent\x18\a \x01(\v2\x19.serialization.FlashEventH\x00R\n" +
	"flashEvent\x12>\n" +
	"\vdamageEvent\x18\b \x01(\v2\x1a.serialization.DamageEventH\x00R\vdamageEvent\x12A\n" +
	"\finfernoEvent\x18\t \x01(\v2\x1b.serialization.InfernoEventH\x00R\finfernoEvent\x12G\n" +
	"\x0eequipmentEvent\x18\n" +
	" \x01(\v2\x1d.serialization.EquipmentEventH\x00R\x0eequipmentEvent\x12>\n" +
	"\vpickupEvent\x18\v \x01(\v2\x1a.serialization.PickupEventH\x00R\vpickupEvent\x128\n" +
	"\tdropEvent\x18\f \x01(\v2\x18.serialization.DropEventH\x00R\tdropEvent\x12M\n" +
	"\x10bombDroppedEvent\x18\r \x01(\v2\x1f.serialization.BombDroppedEventH\x00R\x10bombDroppedEventB\x06\n" +
	"\x04data\"?\n" +
	"\vRoundFrames\x120\n" +
	"\x06frames\x18\x01 \x03(\v2\x18.serialization.FrameDataR\x06frames\"?\n" +
	"\vRoundEvents\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.serialization.GameEventR\x06events\"G\n" +
	"\x0eRoundSnapshots\x125\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x17.serialization.SnapshotR\tsnapshots\"\xd0\x05\n" +
	"\x06Replay\x12\x18\n" +
	"\amapName\x18\x01 \x01(\tR\amapName\x12\x1a\n" +
	"\btickRate\x18\x02 \x01(\x01R\btickRate\x12T\n" +
	"\x0fplayersMetadata\x18\x03 \x03(\v2*.serialization.Replay.PlayersMetadataEntryR\x0fplayersMetadata\x12N\n" +
	"\rnadesMetadata\x18\x04 \x03(\v2(.serialization.Replay.NadesMetadataEntryR\rnadesMetadata\x12D\n" +
	"\x0eroundsMetadata\x18\x05 \x03(\v2\x1c.serialization.RoundMetadataR\x0eroundsMetadata\x122\n" +
	"\x06rounds\x18\x06 \x03(\v2\x1a.serialization.RoundFramesR\x06rounds\x122\n" +
	"\x06events\x18\a \x03(\v2\x1a.serialization.RoundEventsR\x06events\x12;\n" +
	"\tsnapshots\x18\b \x03(\v2\x1d.serialization.RoundSnapshotsR\tsnapshots\x12=\n" +
	"\flast_updated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aa\n" +
	"\x14PlayersMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.serialization.PlayerMetadataR\x05value:\x028\x01\x1a]\n" +
	"\x12NadesMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.serialization.NadeMetadataR\x05value:\x028\x01*\xb6\x02\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vEVENT_FLASH\x10\x01\x12\x15\n" +
	"\x11EVENT_SMOKE_START\x10\x02\x12\x13\n" +
	"\x0fEVENT_SMOKE_END\x10\x03\x12\x0e\n" +
	"\n" +
	"EVENT_KILL\x10\x04\x12\f\n" +
	"\bEVENT_HE\x10\x05\x12\x15\n" +
	"\x11EVENT_TEAM_CHANGE\x10\x06\x12\x11\n" +
	"\rEVENT_INFERNO\x10\a\x12\x10\n" +
	"\fEVENT_DAMAGE\x10\b\x12\x18\n" +
	"\x14EVENT_PLAYER_FLASHED\x10\t\x12\x1a\n" +
	"\x16EVENT_EQUIPMENT_UPDATE\x10\n" +
	"\x12\x10\n" +
	"\fEVENT_PICKUP\x10\v\x12\x0e\n" +
	"\n" +
	"EVENT_DROP\x10\f\x12\x16\n" +
	"\x12EVENT_BOMB_DROPPED\x10\r\x12\x15\n" +
	"\x11EVENT_BOMB_PICKUP\x10\x0eB Z\x1etopdown/internal/serializationb\x06proto3"

var (
	file_serialization_proto_rawDescOnce sync.Once
	file_serialization_proto_rawDescData []byte
)

func file_serialization_proto_rawDescGZIP() []byte {
	file_serialization_proto_rawDescOnce.Do(func() {
		file_serialization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serialization_proto_rawDesc), len(file_serialization_proto_rawDesc)))
	})
	return file_serialization_proto_rawDescData
}

var file_serialization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serialization_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_serialization_proto_goTypes = []any{
	(EventType)(0),              // 0: serialization.EventType
	(*PlayerMetadata)(nil),      // 1: serialization.PlayerMetadata
	(*NadeMetadata)(nil),        // 2: serialization.NadeMetadata
	(*Score)(nil),               // 3: serialization.Score
	(*RoundMetadata)(nil),       // 4: serialization.RoundMetadata
	(*PlayerPosition)(nil),      // 5: serialization.PlayerPosition
	(*NadePosition)(nil),        // 6: serialization.NadePosition
	(*FrameData)(nil),           // 7: serialization.FrameData
	(*PlayerEquipment)(nil),     // 8: serialization.PlayerEquipment
	(*PlayerSnapshot)(nil),      // 9: serialization.PlayerSnapshot
	(*BloomSnapshot)(nil),       // 10: serialization.BloomSnapshot
	(*FlashedSnapshot)(nil),     // 11: serialization.FlashedSnapshot
	(*Point)(nil),               // 12: serialization.Point
	(*Points)(nil),              // 13: serialization.Points
	(*ULID)(nil),                // 14: serialization.ULID
	(*Snapshot)(nil),            // 15: serialization.Snapshot
	(*TeamChangeEvent)(nil),     // 16: serialization.TeamChangeEvent
	(*SmokeEvent)(nil),          // 17: serialization.SmokeEvent
	(*GrenadeEvent)(nil),        // 18: serialization.GrenadeEvent
	(*KillEvent)(nil),           // 19: serialization.KillEvent
	(*DamageEvent)(nil),         // 20: serialization.DamageEvent
	(*InfernoEvent)(nil),        // 21: serialization.InfernoEvent
	(*FlashEvent)(nil),          // 22: serialization.FlashEvent
	(*EquipmentEvent)(nil),      // 23: serialization.EquipmentEvent
	(*PickupEvent)(nil),         // 24: serialization.PickupEvent
	(*DropEvent)(nil),           // 25: serialization.DropEvent
	(*BombDroppedEvent)(nil),    // 26: serialization.BombDroppedEvent
	(*GameEvent)(nil),           // 27: serialization.GameEvent
	(*RoundFrames)(nil),         // 28: serialization.RoundFrames
	(*RoundEvents)(nil),         // 29: serialization.RoundEvents
	(*RoundSnapshots)(nil),      // 30: serialization.RoundSnapshots
	(*Replay)(nil),              // 31: serialization.Replay
	nil,                         // 32: serialization.RoundMetadata.PlayerToTeamEntry
	nil,                         // 33: serialization.RoundMetadata.PlayerToEquipmentEntry
	nil,                         // 34: serialization.FrameData.PlayerPositionsEntry
	nil,                         // 35: serialization.FrameData.NadePositionsEntry
	nil,                         // 36: serialization.Snapshot.PlayerSnapshotsEntry
	nil,                         // 37: serialization.Snapshot.BloomSnapshotsEntry
	nil,                         // 38: serialization.Snapshot.InfernoSnapshotsEntry
	nil,                         // 39: serialization.Snapshot.FlashedSnapshotsEntry
	nil,                         // 40: serialization.Replay.PlayersMetadataEntry
	nil,                         // 41: serialization.Replay.NadesMetadataEntry
	(*timestamp.Timestamp)(nil), // 42: google.protobuf.Timestamp
}
var file_serialization_proto_depIdxs = []int32{
	3,  // 0: serialization.RoundMetadata.score:type_name -> serialization.Score
	32, // 1: serialization.RoundMetadata.playerToTeam:type_name -> serialization.RoundMetadata.PlayerToTeamEntry
	33, // 2: serialization.RoundMetadata.playerToEquipment:type_name -> serialization.RoundMetadata.PlayerToEquipmentEntry
	34, // 3: serialization.FrameData.playerPositions:type_name -> serialization.FrameData.PlayerPositionsEntry
	35, // 4: serialization.FrameData.nadePositions:type_name -> serialization.FrameData.NadePositionsEntry
	12, // 5: serialization.Points.points:type_name -> serialization.Point
	36, // 6: serialization.Snapshot.playerSnapshots:type_name -> serialization.Snapshot.PlayerSnapshotsEntry
	37, // 7: serialization.Snapshot.bloomSnapshots:type_name -> serialization.Snapshot.BloomSnapshotsEntry
	38, // 8: serialization.Snapshot.infernoSnapshots:type_name -> serialization.Snapshot.InfernoSnapshotsEntry
	39, // 9: serialization.Snapshot.flashedSnapshots:type_name -> serialization.Snapshot.FlashedSnapshotsEntry
	12, // 10: serialization.Snapshot.bombSnapshot:type_name -> serialization.Point
	12, // 11: serialization.InfernoEvent.points:type_name -> serialization.Point
	12, // 12: serialization.DropEvent.position:type_name -> serialization.Point
	12, // 13: serialization.BombDroppedEvent.position:type_name -> serialization.Point
	0,  // 14: serialization.GameEvent.type:type_name -> serialization.EventType
	16, // 15: serialization.GameEvent.teamChangeEvent:type_name -> serialization.TeamChangeEvent
	17, // 16: serialization.GameEvent.smokeEvent:type_name -> serialization.SmokeEvent
	18, // 17: serialization.GameEvent.grenadeEvent:type_name -> serialization.GrenadeEvent
	19, // 18: serialization.GameEvent.killEvent:type_name -> serialization.KillEvent
	22, // 19: serialization.GameEvent.flashEvent:type_name -> serialization.FlashEvent
	20, // 20: serialization.GameEvent.damageEvent:type_name -> serialization.DamageEvent
	21, // 21: serialization.GameEvent.infernoEvent:type_name -> serialization.InfernoEvent
	23, // 22: serialization.GameEvent.equipmentEvent:type_name -> serialization.EquipmentEvent
	24, // 23: serialization.GameEvent.pickupEvent:type_name -> serialization.PickupEvent
	25, // 24: serialization.GameEvent.dropEvent:type_name -> serialization.DropEvent
	26, // 25: serialization.GameEvent.bombDroppedEvent:type_name -> serialization.BombDroppedEvent
	7,  // 26: serialization.RoundFrames.frames:type_name -> serialization.FrameData
	27, // 27: serialization.RoundEvents.events:type_name -> serialization.GameEvent
	15, // 28: serialization.RoundSnapshots.snapshots:type_name -> serialization.Snapshot
	40, // 29: serialization.Replay.playersMetadata:type_name -> serialization.Replay.PlayersMetadataEntry
	41, // 30: serialization.Replay.nadesMetadata:type_name -> serialization.Replay.NadesMetadataEntry
	4,  // 31: serialization.Replay.roundsMetadata:type_name -> serialization.RoundMetadata
	28, // 32: serialization.Replay.rounds:type_name -> serialization.RoundFrames
	29, // 33: serialization.Replay.events:type_name -> serialization.RoundEvents
	30, // 34: serialization.Replay.snapshots:type_name -> serialization.RoundSnapshots
	42, // 35: serialization.Replay.last_updated:type_name -> google.protobuf.Timestamp
	8,  // 36: serialization.RoundMetadata.PlayerToEquipmentEntry.value:type_name -> serialization.PlayerEquipment
	5,  // 37: serialization.FrameData.PlayerPositionsEntry.value:type_name -> serialization.PlayerPosition
	6,  // 38: serialization.FrameData.NadePositionsEntry.value:type_name -> serialization.NadePosition
	9,  // 39: serialization.Snapshot.PlayerSnapshotsEntry.value:type_name -> serialization.PlayerSnapshot
	10, // 40: serialization.Snapshot.BloomSnapshotsEntry.value:type_name -> serialization.BloomSnapshot
	13, // 41: serialization.Snapshot.InfernoSnapshotsEntry.value:type_name -> serialization.Points
	11, // 42: serialization.Snapshot.FlashedSnapshotsEntry.value:type_name -> serialization.FlashedSnapshot
	1,  // 43: serialization.Replay.PlayersMetadataEntry.value:type_name -> serialization.PlayerMetadata
	2,  // 44: serialization.Replay.NadesMetadataEntry.value:type_name -> serialization.NadeMetadata
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_serialization_proto_init() }
func file_serialization_proto_init() {
	if File_serialization_proto != nil {
		return
	}
	file_serialization_proto_msgTypes[26].OneofWrappers = []any{
		(*GameEvent_TeamChangeEvent)(nil),
		(*GameEvent_SmokeEvent)(nil),
		(*GameEvent_GrenadeEvent)(nil),
		(*GameEvent_KillEvent)(nil),
		(*GameEvent_FlashEvent)(nil),
		(*GameEvent_DamageEvent)(nil),
		(*GameEvent_InfernoEvent)(nil),
		(*GameEvent_EquipmentEvent)(nil),
		(*GameEvent_PickupEvent)(nil),
		(*GameEvent_DropEvent)(nil),
		(*GameEvent_BombDroppedEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serialization_proto_rawDesc), len(file_serialization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serialization_proto_goTypes,
		DependencyIndexes: file_serialization_proto_depIdxs,
		EnumInfos:         file_serialization_proto_enumTypes,
		MessageInfos:      file_serialization_proto_msgTypes,
	}.Build()
	File_serialization_proto = out.File
	file_serialization_proto_goTypes = nil
	file_serialization_proto_depIdxs = nil
}
